---
extends: default

ignore: |
  venv/

rules:
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  document-start:
    present: true
  line-length: false
  quoted-strings:
    quote-type: single
    required: only-when-needed
