---
name: Test

'on':
  push:
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Build Environment
        id: env
        run: |
          echo ::set-output name=CONTAINER_RUNTIME::$(which podman 2>/dev/null || which docker)

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache Python Dependencies
        uses: actions/cache@v2
        id: cache_python
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install Python Dependencies
        if: steps.cache_python.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade --upgrade-strategy eager pip
          python3 -m pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Lint with Molecule
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        run: molecule -c molecule.yml lint -s lint

      - name: Test with Molecule
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          for ROLE_DIR in roles/*/; do
            pushd "${ROLE_DIR}" &>/dev/null
            echo "::group::Testing role $(basename "${ROLE_DIR}")"
            molecule -c ../../molecule.yml test --all | grep -Ev '(::group::|::endgroup::)'
            echo "::endgroup::"
            popd &>/dev/null
          done
